require 'huginn_agent'

#HuginnAgent.load 'huginn_teamspeak3_version_checker_agent/concerns/my_agent_concern'
HuginnAgent.register 'huginn_teamspeak3_version_checker_agent/teamspeak3_version_checker_agent'
